name: aligning-construals
channels:
- pytorch
- defaults
dependencies:
- python=3.9
- pip
- ipython
- torchvision
- pip:
  - click
  - cloudpickle
  - gym>=0.18.3
  - matplotlib
  - numpy>=1.20.3
  #- mujoco-py<2.1,>=2.0
  - tqdm
  - seaborn